### ISSUE TITLE
Zoom into image on Android

### ISSUE THREAD

**Issue by stephanj** [devoxx/MyDevoxxGluon#55] opened 2018-05-15 09:40 UTC
It's almost not possible to zoom into the venue images on Android.   
Does work very well on iOS.

![image](https://user-images.githubusercontent.com/179457/40049322-c4c70214-5834-11e8-9467-8286dc50b31f.png)

**Comment by jperedadnr** [comment] 2018-05-30 12:10
I didn't realize this issue, and created #62, and provided a fix for it (PR #63)

**Comment by erwin1** [comment] 2018-06-04 20:06
duplicate of #62

**Closed by erwin1** 2018-06-04 20:06 UTC
Labels: enhancement
